


version: '3.8'

networks:
    budget:
      external: true

services:
    webhook:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - "/app/node_modules"
            - ".:/app"
        command: npm run app
        # command: node_modules/.bin/nodemon -L index.js
        networks:
            - budget
        env_file: .env
