


version: '3.8'

volumes:
    pg3:
      external: true

networks:
    budget:
      external: true

services:
    database:
        container_name: pg_db
        image: postgres:13.0
        ports:
            - "5432:5432"
        networks:
            - budget
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=local_fgr_budget
        volumes:
            - "pg3:/var/lib/postgresql/data"
    webhook:
        container_name: webhook_backend
        build: .
        ports:
            - "3000:3000"
        volumes:
            - "/app/node_modules"
            - ".:/app"
        command: npm run app
        networks:
            - budget
        env_file: .env
