name: Build Docker

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-build-tag-push-docker-images:
    name: Build, Tag, Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: get git sha 
        run: |
          echo "sha": $GITHUB_SHA

    
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build image based on date
      #   run: |
      #     CURRENT_DATETIME=$(date "+%Y-%m-%d-%H-%M-%S")
      #     docker build -t dariv94/kubebud_webhook:$CURRENT_DATETIME .

      # - name: Tag a couple other helpful images
      #   run: |
      #     docker tag dariv94/kubebud_webhook:$CURRENT_DATETIME dariv94/kubebud_webhook:${GITHUB_SHA}
      #     docker tag dariv94/kubebud_webhook:$CURRENT_DATETIME dariv94/kubebud_webhook:latest

      # - name: Push images to docker hub
      #   run: |
      #     docker push dariv94/kubebud_webhook:$CURRENT_DATETIME 
      #     docker push dariv94/kubebud_webhook:${GITHUB_SHA} 
      #     docker push dariv94/kubebud_webhook:latest

  